language: python

python:
  - "3.6"
  
install:
  - pip3 install -r requirements.txt

services:
 - postgresql

before_script:
 - psql -c 'CREATE DATABASE SendIT;' -U postgres
 - export DB_TEST="dbname='SendIT' host='localhost' port='5432' user='postgres' password= '' "
 - export FLASK_ENV=testing


script: coverage run --source=api -m pytest && coverage report

after_success: coveralls

notifications:
  email: false
  